services:
  - type: web
    name: budget-bot
    runtime: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: credentials.json
    pythonVersion: 3.10
